Improvemnts to instant
ColinEberhardt/assemblyscript-temporal pull request #58
Opened 2021-05-19 19:48 UTC by SebastianSpeitel

Use preexisting methods and constants
Don't create temporary duration instances if possible

2021-05-20 07:01 UTC, ColinEberhardt commented
Thanks for these changes, much appreciated.

> Don't create temporary duration instances if possible

In this instance, I'd prefer to keep the code the way it was. At the moment I am undertaking a fairly significant refactoring of the codebase (see this branch https://github.com/ColinEberhardt/assemblyscript-temporal/tree/refactor). It helps to keep the code simple (rather than performance optimised) during refactor.

Performance optimisation can be a step after that!

2021-05-20 07:02 UTC, ColinEberhardt requested changes

2021-05-20 07:02 UTC, ColinEberhardt commented on assembly/instant.ts
> +    const duration =
please revert as per comment on PR

2021-05-20 07:02 UTC, ColinEberhardt commented on assembly/instant.ts
> +    const duration =
please revert as per comment on PR

2021-05-25 15:00 UTC, SebastianSpeitel commented
Now this PR only includes the constants.

2021-05-25 21:22 UTC, merged

2021-05-25 21:22 UTC, ColinEberhardt commented
Thanks @SebastianSpeitel